#include <cstdlib>
#include <vector>
#include <algorithm>
#include <iostream>

#include <OpenMesh/Core/IO/MeshIO.hh>
#include <OpenMesh/Core/Mesh/PolyMesh_ArrayKernelT.hh>

typedef OpenMesh::PolyMesh_ArrayKernelT<> MyMesh;

void WriteUnstr(std::vector<MyMesh*> &layers, const char *strFileName)
{

  using namespace std;
  FILE * myfile = fopen(strFileName,"w");

  if (myfile == NULL) {
    cout<<"Error opening file: "<<strFileName<<endl;
    exit(0);
  }  

  int totalVertices = 0;

  int i;
  fprintf(myfile,"# vtk DataFile Version 2.0\n");
  fprintf(myfile,"Generated by FullC0ntact\n");
  fprintf(myfile,"ASCII\n");
  fprintf(myfile,"DATASET UNSTRUCTURED_GRID\n");
  fprintf(myfile,"POINTS %i double\n", totalVertices);      

  for(i=0; i < totalVertices; i++)
  {
//    fprintf(myfile,"%f %f %f \n",Grid.vertexCoords_[i].x,Grid.vertexCoords_[i].y,Grid.vertexCoords_[i].z);    
  }//end for

  //int nfaces = Grid.facesAtBoundary_.size();
//  ParFileInfo &xx = Grid.parInfo_->front();
//  int nfaces = xx.faces_.size();
//
//  fprintf(myfile,"CELLS %i %i\n",nfaces,nfaces*5);
//  for(i=0;i<nfaces;i++)
//  {
//    int i0 = xx.verticesAtFace_[i].faceVertexIndices_[0];
//    int i1 = xx.verticesAtFace_[i].faceVertexIndices_[1];
//    int i2 = xx.verticesAtFace_[i].faceVertexIndices_[2];
//    int i3 = xx.verticesAtFace_[i].faceVertexIndices_[3];
//    fprintf(myfile,"4  %i %i %i %i\n",i0,i1,i2,i3);
//  }//end for
//
//  fprintf(myfile,"CELL_TYPES %i\n",nfaces);        
//  for(i=0;i<nfaces;i++)
//  {
//    fprintf(myfile,"9\n");          
//  }//end for

  //close the file
  fclose (myfile);  

}

void writeOFFMesh(MyMesh& mesh) {

  try {
    if (!OpenMesh::IO::write_mesh(mesh, "output.off")) {
      std::cerr << "Cannot write mesh to file 'output.off'" << std::endl;
      std::exit(EXIT_FAILURE);
    }
  }
  catch( std::exception &x) {
    std::cerr << x.what() << std::endl;
    std::exit(EXIT_FAILURE);
  }

}

void buildSimpleCube() {

  MyMesh mesh;

  MyMesh::VertexHandle vhandle[8];

  MyMesh::Point vertices[] = {
    MyMesh::Point(-1, -1, 1), 
    MyMesh::Point( 1, -1, 1),
    MyMesh::Point( 1,  1, 1),
    MyMesh::Point(-1,  1, 1),
    MyMesh::Point(-1, -1,-1),
    MyMesh::Point( 1, -1,-1),
    MyMesh::Point( 1,  1,-1),
    MyMesh::Point(-1,  1,-1)
  };

  int connectivity[][4] = { {0, 1, 2, 3}, {7, 6, 5, 4}, {1, 0, 4, 5}, {2, 1, 5, 6}, {3, 2, 6, 7}, {0, 3, 7, 4} };

  for (unsigned i(0); i < 8; ++i) {
    vhandle[i] = mesh.add_vertex(vertices[i]);
  }

  std::vector<MyMesh::VertexHandle> face_vhandles;

  for (unsigned i(0); i < 6; ++i) {
    face_vhandles.clear();
    face_vhandles.push_back(vhandle[connectivity[i][0]]);
    face_vhandles.push_back(vhandle[connectivity[i][1]]);
    face_vhandles.push_back(vhandle[connectivity[i][2]]);
    face_vhandles.push_back(vhandle[connectivity[i][3]]);
    mesh.add_face(face_vhandles);
  }

  writeOFFMesh(mesh);

}

int main()
{
  buildSimpleCube();
  return EXIT_SUCCESS;
}
